# headers and icon 
title: Sohag Kumar Saha
info: PhD in ECE @ TnTech
icon-pic: assets/img/hello_emoji.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
